/**
 * Allowed workflow states for a task.
 * Valid values: "todo", "in-progress", "done".
 */
export type TaskStatus = "todo" | "in-progress" | "done";

/**
 * Canonical task entity returned by the API.
 */
export interface Task {
  /**
   * Unique task identifier.
   * Expected format: UUID string generated by the server.
   */
  id: string;

  /**
   * Short task summary.
   * Valid range: non-empty string (trimmed length >= 1).
   */
  title: string;

  /**
   * Detailed task description.
   * Valid range: non-empty string (trimmed length >= 1).
   */
  description: string;

  /**
   * Current task state.
   * Valid values: "todo", "in-progress", "done".
   */
  status: TaskStatus;

  /**
   * Timestamp when the task was created.
   * Expected format: ISO 8601 UTC datetime string.
   */
  createdAt: string;

  /**
   * Timestamp when the task was last updated.
   * Expected format: ISO 8601 UTC datetime string.
   */
  updatedAt: string;
}

/**
 * Input payload for creating a task.
 */
export interface CreateTaskInput {
  /**
   * Short task summary.
   * Valid range: non-empty string (trimmed length >= 1).
   */
  title: string;

  /**
   * Detailed task description.
   * Valid range: non-empty string (trimmed length >= 1).
   */
  description: string;

  /**
   * Initial task state.
   * Valid values: "todo", "in-progress", "done".
   */
  status: TaskStatus;
}

/**
 * Input payload for replacing a task.
 */
export interface UpdateTaskInput {
  /**
   * Updated task summary.
   * Valid range: non-empty string (trimmed length >= 1).
   */
  title: string;

  /**
   * Updated task description.
   * Valid range: non-empty string (trimmed length >= 1).
   */
  description: string;

  /**
   * Updated task state.
   * Valid values: "todo", "in-progress", "done".
   */
  status: TaskStatus;
}
